service:
  name: k8s
  identifier: k8s
  serviceDefinition:
    type: Kubernetes
    spec:
      manifests:
        - manifest:
            identifier: deployment
            type: DeploymentRepo
            spec:
              store:
                type: Github
                spec:
                  connectorRef: github2
                  gitFetchType: Branch
                  paths:
                    - deployment.yaml
                  branch: master
                  repoName: node-app
  gitOpsEnabled: true
  orgIdentifier: default
  projectIdentifier: rebellis
