name: CI

on:
  push:
    branches:
    - main
  workflow_dispatch:
env:
  name: stag
  IMAGE_NAME: dpnode-stag

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    # - name: Login to DockerHub
    #   uses: docker/login-action@v1
    #   with:
    #     username: ${{ secrets.DOCKERHUB_USERNAME }}
    #     password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        # Container registry username
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        # Container registry password
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Container registry server url
        login-server: ${{ vars.ACR_URL }}    
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}

    # - name: Repository Dispatch
    #   uses: peter-evans/repository-dispatch@v1
    #   with:
    #     token: ${{ secrets.PAT }}
    #     repository: ${{ github.actor }}/argocd-node-app-config
    #     event-type: new-image
    #     client-payload: '{"image": "${{ github.actor }}/${{ env.IMAGE_NAME }}:${{ github.run_number }}"}'
